### ISSUE TITLE
Shulkers

### ISSUE THREAD

**Issue by kompot7** [rossnoah/PerPlayerKit#13]
chalkers become empty after interacting with the plugin (be it /ec, /k, and so on)
, that is, if you put something in a chalker and save it and take a whale with a chalker or an ender chest, it will be empty.
And viewing shalkers is not available in kitroom

**Comment by rossnoah** [comment]
Try setting these settings to false in your config. 

### **Anti-Exploit**

This section allows you to enable or disable anti-exploit features, commonly applicable to this plugin.

```yaml
anti-exploit:
  only-allow-kitroom-items: false #requires that items be in the kitroom before they can be used in a kit.
  import-filter: false #requires only-allow-kitroom-items to be true. prevents the duplications of items not in the kitroom by using the kit import button.
  block-spaces-in-commands: false #prevents bypassing command filters.
  prevent-shulkers-dropping-items: false #prevents shulkers from dropping items when broken. Anti-lag feature.
```
